# Generated by Django 2.0 on 2018-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181019_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='constructeur',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
