# Generated by Django 2.0 on 2018-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181019_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouton',
            name='id_action',
            field=models.IntegerField(default=0),
        ),
    ]
