# Generated by Django 2.0 on 2018-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181019_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LinkButtonAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_button', models.IntegerField(default=0)),
                ('id_action', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectConnected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField(default=0)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('brand', models.CharField(default='default_brand', max_length=100)),
                ('reference', models.CharField(default='default_reference', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bouton',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='descriptif',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='id_object',
            new_name='id_objet_connected',
        ),
    ]
