# Generated by Django 2.0 on 2018-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181019_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='default_brand', max_length=100)),
                ('reference', models.CharField(default='default_reference', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='objectconnected',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='objectconnected',
            name='reference',
        ),
        migrations.AddField(
            model_name='objectconnected',
            name='id_allObject',
            field=models.IntegerField(default=0),
        ),
    ]
